package com.bit.solana.proto.block;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: structure.proto
// Protobuf Java Version: 4.31.1

@com.google.protobuf.Generated
public final class Structure {
  private Structure() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Structure.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoBlockHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBlockHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes previous_block_hash = 1;</code>
     * @return The previousBlockHash.
     */
    com.google.protobuf.ByteString getPreviousBlockHash();

    /**
     * <code>bytes state_root_hash = 2;</code>
     * @return The stateRootHash.
     */
    com.google.protobuf.ByteString getStateRootHash();
  }
  /**
   * <pre>
   * protoc --proto_path=. --java_out=. structure.proto
   * </pre>
   *
   * Protobuf type {@code ProtoBlockHeader}
   */
  public static final class ProtoBlockHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoBlockHeader)
      ProtoBlockHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ProtoBlockHeader.class.getName());
    }
    // Use ProtoBlockHeader.newBuilder() to construct.
    private ProtoBlockHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtoBlockHeader() {
      previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Structure.internal_static_ProtoBlockHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Structure.internal_static_ProtoBlockHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Structure.ProtoBlockHeader.class, Structure.ProtoBlockHeader.Builder.class);
    }

    public static final int PREVIOUS_BLOCK_HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes previous_block_hash = 1;</code>
     * @return The previousBlockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPreviousBlockHash() {
      return previousBlockHash_;
    }

    public static final int STATE_ROOT_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes state_root_hash = 2;</code>
     * @return The stateRootHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStateRootHash() {
      return stateRootHash_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!previousBlockHash_.isEmpty()) {
        output.writeBytes(1, previousBlockHash_);
      }
      if (!stateRootHash_.isEmpty()) {
        output.writeBytes(2, stateRootHash_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!previousBlockHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, previousBlockHash_);
      }
      if (!stateRootHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, stateRootHash_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Structure.ProtoBlockHeader)) {
        return super.equals(obj);
      }
      Structure.ProtoBlockHeader other = (Structure.ProtoBlockHeader) obj;

      if (!getPreviousBlockHash()
          .equals(other.getPreviousBlockHash())) return false;
      if (!getStateRootHash()
          .equals(other.getStateRootHash())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREVIOUS_BLOCK_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousBlockHash().hashCode();
      hash = (37 * hash) + STATE_ROOT_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getStateRootHash().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Structure.ProtoBlockHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Structure.ProtoBlockHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Structure.ProtoBlockHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Structure.ProtoBlockHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * protoc --proto_path=. --java_out=. structure.proto
     * </pre>
     *
     * Protobuf type {@code ProtoBlockHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBlockHeader)
        Structure.ProtoBlockHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Structure.internal_static_ProtoBlockHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Structure.internal_static_ProtoBlockHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Structure.ProtoBlockHeader.class, Structure.ProtoBlockHeader.Builder.class);
      }

      // Construct using Structure.ProtoBlockHeader.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
        stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Structure.internal_static_ProtoBlockHeader_descriptor;
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader getDefaultInstanceForType() {
        return Structure.ProtoBlockHeader.getDefaultInstance();
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader build() {
        Structure.ProtoBlockHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader buildPartial() {
        Structure.ProtoBlockHeader result = new Structure.ProtoBlockHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Structure.ProtoBlockHeader result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.previousBlockHash_ = previousBlockHash_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stateRootHash_ = stateRootHash_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Structure.ProtoBlockHeader) {
          return mergeFrom((Structure.ProtoBlockHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Structure.ProtoBlockHeader other) {
        if (other == Structure.ProtoBlockHeader.getDefaultInstance()) return this;
        if (!other.getPreviousBlockHash().isEmpty()) {
          setPreviousBlockHash(other.getPreviousBlockHash());
        }
        if (!other.getStateRootHash().isEmpty()) {
          setStateRootHash(other.getStateRootHash());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                previousBlockHash_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                stateRootHash_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes previous_block_hash = 1;</code>
       * @return The previousBlockHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPreviousBlockHash() {
        return previousBlockHash_;
      }
      /**
       * <code>bytes previous_block_hash = 1;</code>
       * @param value The previousBlockHash to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        previousBlockHash_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes previous_block_hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousBlockHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        previousBlockHash_ = getDefaultInstance().getPreviousBlockHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes state_root_hash = 2;</code>
       * @return The stateRootHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStateRootHash() {
        return stateRootHash_;
      }
      /**
       * <code>bytes state_root_hash = 2;</code>
       * @param value The stateRootHash to set.
       * @return This builder for chaining.
       */
      public Builder setStateRootHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        stateRootHash_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes state_root_hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateRootHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stateRootHash_ = getDefaultInstance().getStateRootHash();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoBlockHeader)
    }

    // @@protoc_insertion_point(class_scope:ProtoBlockHeader)
    private static final Structure.ProtoBlockHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Structure.ProtoBlockHeader();
    }

    public static Structure.ProtoBlockHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoBlockHeader>
        PARSER = new com.google.protobuf.AbstractParser<ProtoBlockHeader>() {
      @java.lang.Override
      public ProtoBlockHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtoBlockHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBlockHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Structure.ProtoBlockHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return The header.
     */
    Structure.ProtoBlockHeader getHeader();
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     */
    Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code ProtoBlock}
   */
  public static final class ProtoBlock extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoBlock)
      ProtoBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ProtoBlock.class.getName());
    }
    // Use ProtoBlock.newBuilder() to construct.
    private ProtoBlock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtoBlock() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Structure.internal_static_ProtoBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Structure.internal_static_ProtoBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Structure.ProtoBlock.class, Structure.ProtoBlock.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Structure.ProtoBlockHeader header_;
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public Structure.ProtoBlockHeader getHeader() {
      return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     */
    @java.lang.Override
    public Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Structure.ProtoBlock)) {
        return super.equals(obj);
      }
      Structure.ProtoBlock other = (Structure.ProtoBlock) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Structure.ProtoBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Structure.ProtoBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Structure.ProtoBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Structure.ProtoBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBlock)
        Structure.ProtoBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Structure.internal_static_ProtoBlock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Structure.internal_static_ProtoBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Structure.ProtoBlock.class, Structure.ProtoBlock.Builder.class);
      }

      // Construct using Structure.ProtoBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetHeaderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Structure.internal_static_ProtoBlock_descriptor;
      }

      @java.lang.Override
      public Structure.ProtoBlock getDefaultInstanceForType() {
        return Structure.ProtoBlock.getDefaultInstance();
      }

      @java.lang.Override
      public Structure.ProtoBlock build() {
        Structure.ProtoBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Structure.ProtoBlock buildPartial() {
        Structure.ProtoBlock result = new Structure.ProtoBlock(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Structure.ProtoBlock result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Structure.ProtoBlock) {
          return mergeFrom((Structure.ProtoBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Structure.ProtoBlock other) {
        if (other == Structure.ProtoBlock.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Structure.ProtoBlockHeader header_;
      private com.google.protobuf.SingleFieldBuilder<
          Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       * @return The header.
       */
      public Structure.ProtoBlockHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder setHeader(Structure.ProtoBlockHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder setHeader(
          Structure.ProtoBlockHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder mergeHeader(Structure.ProtoBlockHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != Structure.ProtoBlockHeader.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        if (header_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Structure.ProtoBlockHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              Structure.ProtoBlockHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder> 
          internalGetHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProtoBlock)
    }

    // @@protoc_insertion_point(class_scope:ProtoBlock)
    private static final Structure.ProtoBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Structure.ProtoBlock();
    }

    public static Structure.ProtoBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoBlock>
        PARSER = new com.google.protobuf.AbstractParser<ProtoBlock>() {
      @java.lang.Override
      public ProtoBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtoBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBlock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Structure.ProtoBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBlockHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoBlockHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017structure.proto\"H\n\020ProtoBlockHeader\022\033\n" +
      "\023previous_block_hash\030\001 \001(\014\022\027\n\017state_root" +
      "_hash\030\002 \001(\014\"/\n\nProtoBlock\022!\n\006header\030\001 \001(" +
      "\0132\021.ProtoBlockHeaderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoBlockHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoBlockHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoBlockHeader_descriptor,
        new java.lang.String[] { "PreviousBlockHash", "StateRootHash", });
    internal_static_ProtoBlock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoBlock_descriptor,
        new java.lang.String[] { "Header", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
