package com.bit.solana.proto.block;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: structure.proto
// Protobuf Java Version: 4.31.1

@com.google.protobuf.Generated
public final class Structure {
  private Structure() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Structure.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoBlockHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBlockHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 前序区块哈希（32字节）
     * </pre>
     *
     * <code>bytes previous_block_hash = 1;</code>
     * @return The previousBlockHash.
     */
    com.google.protobuf.ByteString getPreviousBlockHash();

    /**
     * <pre>
     * 状态根哈希（32字节）
     * </pre>
     *
     * <code>bytes state_root_hash = 2;</code>
     * @return The stateRootHash.
     */
    com.google.protobuf.ByteString getStateRootHash();

    /**
     * <pre>
     * 区块提议时间戳（毫秒级）
     * </pre>
     *
     * <code>uint64 block_time = 3;</code>
     * @return The blockTime.
     */
    long getBlockTime();

    /**
     * <pre>
     * PoH哈希（32字节）
     * </pre>
     *
     * <code>bytes poh_hash = 4;</code>
     * @return The pohHash.
     */
    com.google.protobuf.ByteString getPohHash();

    /**
     * <pre>
     * PoH高度
     * </pre>
     *
     * <code>uint64 poh_height = 5;</code>
     * @return The pohHeight.
     */
    long getPohHeight();

    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>uint64 version = 6;</code>
     * @return The version.
     */
    long getVersion();

    /**
     * <pre>
     * 插槽号
     * </pre>
     *
     * <code>uint64 slot = 7;</code>
     * @return The slot.
     */
    long getSlot();

    /**
     * <pre>
     * 父插槽号
     * </pre>
     *
     * <code>uint64 parent_slot = 8;</code>
     * @return The parentSlot.
     */
    long getParentSlot();

    /**
     * <pre>
     * 最近投票哈希（32字节）
     * </pre>
     *
     * <code>bytes recent_votes_hash = 9;</code>
     * @return The recentVotesHash.
     */
    com.google.protobuf.ByteString getRecentVotesHash();

    /**
     * <pre>
     * 领导者调度周期
     * </pre>
     *
     * <code>uint64 leader_schedule_epoch = 10;</code>
     * @return The leaderScheduleEpoch.
     */
    long getLeaderScheduleEpoch();

    /**
     * <pre>
     * 交易数量
     * </pre>
     *
     * <code>uint64 transactions_count = 11;</code>
     * @return The transactionsCount.
     */
    long getTransactionsCount();

    /**
     * <pre>
     * 费用计算器哈希（32字节）
     * </pre>
     *
     * <code>bytes fee_calculator_hash = 12;</code>
     * @return The feeCalculatorHash.
     */
    com.google.protobuf.ByteString getFeeCalculatorHash();

    /**
     * <pre>
     * 交易布隆过滤器（序列化后字节）
     * </pre>
     *
     * <code>bytes tx_bloom_filter = 13;</code>
     * @return The txBloomFilter.
     */
    com.google.protobuf.ByteString getTxBloomFilter();

    /**
     * <pre>
     * 日志布隆过滤器（序列化后字节）
     * </pre>
     *
     * <code>bytes log_bloom_filter = 14;</code>
     * @return The logBloomFilter.
     */
    com.google.protobuf.ByteString getLogBloomFilter();
  }
  /**
   * <pre>
   * protoc --proto_path=. --java_out=. structure.proto
   * </pre>
   *
   * Protobuf type {@code ProtoBlockHeader}
   */
  public static final class ProtoBlockHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoBlockHeader)
      ProtoBlockHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ProtoBlockHeader.class.getName());
    }
    // Use ProtoBlockHeader.newBuilder() to construct.
    private ProtoBlockHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtoBlockHeader() {
      previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
      pohHash_ = com.google.protobuf.ByteString.EMPTY;
      recentVotesHash_ = com.google.protobuf.ByteString.EMPTY;
      feeCalculatorHash_ = com.google.protobuf.ByteString.EMPTY;
      txBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
      logBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Structure.internal_static_ProtoBlockHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Structure.internal_static_ProtoBlockHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Structure.ProtoBlockHeader.class, Structure.ProtoBlockHeader.Builder.class);
    }

    public static final int PREVIOUS_BLOCK_HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 前序区块哈希（32字节）
     * </pre>
     *
     * <code>bytes previous_block_hash = 1;</code>
     * @return The previousBlockHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPreviousBlockHash() {
      return previousBlockHash_;
    }

    public static final int STATE_ROOT_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 状态根哈希（32字节）
     * </pre>
     *
     * <code>bytes state_root_hash = 2;</code>
     * @return The stateRootHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStateRootHash() {
      return stateRootHash_;
    }

    public static final int BLOCK_TIME_FIELD_NUMBER = 3;
    private long blockTime_ = 0L;
    /**
     * <pre>
     * 区块提议时间戳（毫秒级）
     * </pre>
     *
     * <code>uint64 block_time = 3;</code>
     * @return The blockTime.
     */
    @java.lang.Override
    public long getBlockTime() {
      return blockTime_;
    }

    public static final int POH_HASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString pohHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * PoH哈希（32字节）
     * </pre>
     *
     * <code>bytes poh_hash = 4;</code>
     * @return The pohHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPohHash() {
      return pohHash_;
    }

    public static final int POH_HEIGHT_FIELD_NUMBER = 5;
    private long pohHeight_ = 0L;
    /**
     * <pre>
     * PoH高度
     * </pre>
     *
     * <code>uint64 poh_height = 5;</code>
     * @return The pohHeight.
     */
    @java.lang.Override
    public long getPohHeight() {
      return pohHeight_;
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    private long version_ = 0L;
    /**
     * <pre>
     * 协议版本号
     * </pre>
     *
     * <code>uint64 version = 6;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }

    public static final int SLOT_FIELD_NUMBER = 7;
    private long slot_ = 0L;
    /**
     * <pre>
     * 插槽号
     * </pre>
     *
     * <code>uint64 slot = 7;</code>
     * @return The slot.
     */
    @java.lang.Override
    public long getSlot() {
      return slot_;
    }

    public static final int PARENT_SLOT_FIELD_NUMBER = 8;
    private long parentSlot_ = 0L;
    /**
     * <pre>
     * 父插槽号
     * </pre>
     *
     * <code>uint64 parent_slot = 8;</code>
     * @return The parentSlot.
     */
    @java.lang.Override
    public long getParentSlot() {
      return parentSlot_;
    }

    public static final int RECENT_VOTES_HASH_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString recentVotesHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 最近投票哈希（32字节）
     * </pre>
     *
     * <code>bytes recent_votes_hash = 9;</code>
     * @return The recentVotesHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRecentVotesHash() {
      return recentVotesHash_;
    }

    public static final int LEADER_SCHEDULE_EPOCH_FIELD_NUMBER = 10;
    private long leaderScheduleEpoch_ = 0L;
    /**
     * <pre>
     * 领导者调度周期
     * </pre>
     *
     * <code>uint64 leader_schedule_epoch = 10;</code>
     * @return The leaderScheduleEpoch.
     */
    @java.lang.Override
    public long getLeaderScheduleEpoch() {
      return leaderScheduleEpoch_;
    }

    public static final int TRANSACTIONS_COUNT_FIELD_NUMBER = 11;
    private long transactionsCount_ = 0L;
    /**
     * <pre>
     * 交易数量
     * </pre>
     *
     * <code>uint64 transactions_count = 11;</code>
     * @return The transactionsCount.
     */
    @java.lang.Override
    public long getTransactionsCount() {
      return transactionsCount_;
    }

    public static final int FEE_CALCULATOR_HASH_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString feeCalculatorHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 费用计算器哈希（32字节）
     * </pre>
     *
     * <code>bytes fee_calculator_hash = 12;</code>
     * @return The feeCalculatorHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFeeCalculatorHash() {
      return feeCalculatorHash_;
    }

    public static final int TX_BLOOM_FILTER_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString txBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 交易布隆过滤器（序列化后字节）
     * </pre>
     *
     * <code>bytes tx_bloom_filter = 13;</code>
     * @return The txBloomFilter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTxBloomFilter() {
      return txBloomFilter_;
    }

    public static final int LOG_BLOOM_FILTER_FIELD_NUMBER = 14;
    private com.google.protobuf.ByteString logBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 日志布隆过滤器（序列化后字节）
     * </pre>
     *
     * <code>bytes log_bloom_filter = 14;</code>
     * @return The logBloomFilter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogBloomFilter() {
      return logBloomFilter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!previousBlockHash_.isEmpty()) {
        output.writeBytes(1, previousBlockHash_);
      }
      if (!stateRootHash_.isEmpty()) {
        output.writeBytes(2, stateRootHash_);
      }
      if (blockTime_ != 0L) {
        output.writeUInt64(3, blockTime_);
      }
      if (!pohHash_.isEmpty()) {
        output.writeBytes(4, pohHash_);
      }
      if (pohHeight_ != 0L) {
        output.writeUInt64(5, pohHeight_);
      }
      if (version_ != 0L) {
        output.writeUInt64(6, version_);
      }
      if (slot_ != 0L) {
        output.writeUInt64(7, slot_);
      }
      if (parentSlot_ != 0L) {
        output.writeUInt64(8, parentSlot_);
      }
      if (!recentVotesHash_.isEmpty()) {
        output.writeBytes(9, recentVotesHash_);
      }
      if (leaderScheduleEpoch_ != 0L) {
        output.writeUInt64(10, leaderScheduleEpoch_);
      }
      if (transactionsCount_ != 0L) {
        output.writeUInt64(11, transactionsCount_);
      }
      if (!feeCalculatorHash_.isEmpty()) {
        output.writeBytes(12, feeCalculatorHash_);
      }
      if (!txBloomFilter_.isEmpty()) {
        output.writeBytes(13, txBloomFilter_);
      }
      if (!logBloomFilter_.isEmpty()) {
        output.writeBytes(14, logBloomFilter_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!previousBlockHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, previousBlockHash_);
      }
      if (!stateRootHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, stateRootHash_);
      }
      if (blockTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, blockTime_);
      }
      if (!pohHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, pohHash_);
      }
      if (pohHeight_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, pohHeight_);
      }
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, version_);
      }
      if (slot_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, slot_);
      }
      if (parentSlot_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, parentSlot_);
      }
      if (!recentVotesHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, recentVotesHash_);
      }
      if (leaderScheduleEpoch_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, leaderScheduleEpoch_);
      }
      if (transactionsCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, transactionsCount_);
      }
      if (!feeCalculatorHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, feeCalculatorHash_);
      }
      if (!txBloomFilter_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, txBloomFilter_);
      }
      if (!logBloomFilter_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, logBloomFilter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Structure.ProtoBlockHeader)) {
        return super.equals(obj);
      }
      Structure.ProtoBlockHeader other = (Structure.ProtoBlockHeader) obj;

      if (!getPreviousBlockHash()
          .equals(other.getPreviousBlockHash())) return false;
      if (!getStateRootHash()
          .equals(other.getStateRootHash())) return false;
      if (getBlockTime()
          != other.getBlockTime()) return false;
      if (!getPohHash()
          .equals(other.getPohHash())) return false;
      if (getPohHeight()
          != other.getPohHeight()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getSlot()
          != other.getSlot()) return false;
      if (getParentSlot()
          != other.getParentSlot()) return false;
      if (!getRecentVotesHash()
          .equals(other.getRecentVotesHash())) return false;
      if (getLeaderScheduleEpoch()
          != other.getLeaderScheduleEpoch()) return false;
      if (getTransactionsCount()
          != other.getTransactionsCount()) return false;
      if (!getFeeCalculatorHash()
          .equals(other.getFeeCalculatorHash())) return false;
      if (!getTxBloomFilter()
          .equals(other.getTxBloomFilter())) return false;
      if (!getLogBloomFilter()
          .equals(other.getLogBloomFilter())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREVIOUS_BLOCK_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getPreviousBlockHash().hashCode();
      hash = (37 * hash) + STATE_ROOT_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getStateRootHash().hashCode();
      hash = (37 * hash) + BLOCK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlockTime());
      hash = (37 * hash) + POH_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getPohHash().hashCode();
      hash = (37 * hash) + POH_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPohHeight());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + SLOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSlot());
      hash = (37 * hash) + PARENT_SLOT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getParentSlot());
      hash = (37 * hash) + RECENT_VOTES_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getRecentVotesHash().hashCode();
      hash = (37 * hash) + LEADER_SCHEDULE_EPOCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeaderScheduleEpoch());
      hash = (37 * hash) + TRANSACTIONS_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTransactionsCount());
      hash = (37 * hash) + FEE_CALCULATOR_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getFeeCalculatorHash().hashCode();
      hash = (37 * hash) + TX_BLOOM_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getTxBloomFilter().hashCode();
      hash = (37 * hash) + LOG_BLOOM_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getLogBloomFilter().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Structure.ProtoBlockHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Structure.ProtoBlockHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Structure.ProtoBlockHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Structure.ProtoBlockHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * protoc --proto_path=. --java_out=. structure.proto
     * </pre>
     *
     * Protobuf type {@code ProtoBlockHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBlockHeader)
        Structure.ProtoBlockHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Structure.internal_static_ProtoBlockHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Structure.internal_static_ProtoBlockHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Structure.ProtoBlockHeader.class, Structure.ProtoBlockHeader.Builder.class);
      }

      // Construct using Structure.ProtoBlockHeader.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
        stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
        blockTime_ = 0L;
        pohHash_ = com.google.protobuf.ByteString.EMPTY;
        pohHeight_ = 0L;
        version_ = 0L;
        slot_ = 0L;
        parentSlot_ = 0L;
        recentVotesHash_ = com.google.protobuf.ByteString.EMPTY;
        leaderScheduleEpoch_ = 0L;
        transactionsCount_ = 0L;
        feeCalculatorHash_ = com.google.protobuf.ByteString.EMPTY;
        txBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
        logBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Structure.internal_static_ProtoBlockHeader_descriptor;
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader getDefaultInstanceForType() {
        return Structure.ProtoBlockHeader.getDefaultInstance();
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader build() {
        Structure.ProtoBlockHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Structure.ProtoBlockHeader buildPartial() {
        Structure.ProtoBlockHeader result = new Structure.ProtoBlockHeader(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Structure.ProtoBlockHeader result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.previousBlockHash_ = previousBlockHash_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stateRootHash_ = stateRootHash_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.blockTime_ = blockTime_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.pohHash_ = pohHash_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.pohHeight_ = pohHeight_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.slot_ = slot_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.parentSlot_ = parentSlot_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.recentVotesHash_ = recentVotesHash_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.leaderScheduleEpoch_ = leaderScheduleEpoch_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.transactionsCount_ = transactionsCount_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.feeCalculatorHash_ = feeCalculatorHash_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.txBloomFilter_ = txBloomFilter_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.logBloomFilter_ = logBloomFilter_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Structure.ProtoBlockHeader) {
          return mergeFrom((Structure.ProtoBlockHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Structure.ProtoBlockHeader other) {
        if (other == Structure.ProtoBlockHeader.getDefaultInstance()) return this;
        if (!other.getPreviousBlockHash().isEmpty()) {
          setPreviousBlockHash(other.getPreviousBlockHash());
        }
        if (!other.getStateRootHash().isEmpty()) {
          setStateRootHash(other.getStateRootHash());
        }
        if (other.getBlockTime() != 0L) {
          setBlockTime(other.getBlockTime());
        }
        if (!other.getPohHash().isEmpty()) {
          setPohHash(other.getPohHash());
        }
        if (other.getPohHeight() != 0L) {
          setPohHeight(other.getPohHeight());
        }
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.getSlot() != 0L) {
          setSlot(other.getSlot());
        }
        if (other.getParentSlot() != 0L) {
          setParentSlot(other.getParentSlot());
        }
        if (!other.getRecentVotesHash().isEmpty()) {
          setRecentVotesHash(other.getRecentVotesHash());
        }
        if (other.getLeaderScheduleEpoch() != 0L) {
          setLeaderScheduleEpoch(other.getLeaderScheduleEpoch());
        }
        if (other.getTransactionsCount() != 0L) {
          setTransactionsCount(other.getTransactionsCount());
        }
        if (!other.getFeeCalculatorHash().isEmpty()) {
          setFeeCalculatorHash(other.getFeeCalculatorHash());
        }
        if (!other.getTxBloomFilter().isEmpty()) {
          setTxBloomFilter(other.getTxBloomFilter());
        }
        if (!other.getLogBloomFilter().isEmpty()) {
          setLogBloomFilter(other.getLogBloomFilter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                previousBlockHash_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                stateRootHash_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                blockTime_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                pohHash_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                pohHeight_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                version_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                slot_ = input.readUInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                parentSlot_ = input.readUInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                recentVotesHash_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 80: {
                leaderScheduleEpoch_ = input.readUInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 88: {
                transactionsCount_ = input.readUInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 98: {
                feeCalculatorHash_ = input.readBytes();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 106: {
                txBloomFilter_ = input.readBytes();
                bitField0_ |= 0x00001000;
                break;
              } // case 106
              case 114: {
                logBloomFilter_ = input.readBytes();
                bitField0_ |= 0x00002000;
                break;
              } // case 114
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString previousBlockHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 前序区块哈希（32字节）
       * </pre>
       *
       * <code>bytes previous_block_hash = 1;</code>
       * @return The previousBlockHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPreviousBlockHash() {
        return previousBlockHash_;
      }
      /**
       * <pre>
       * 前序区块哈希（32字节）
       * </pre>
       *
       * <code>bytes previous_block_hash = 1;</code>
       * @param value The previousBlockHash to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousBlockHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        previousBlockHash_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 前序区块哈希（32字节）
       * </pre>
       *
       * <code>bytes previous_block_hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousBlockHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        previousBlockHash_ = getDefaultInstance().getPreviousBlockHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateRootHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 状态根哈希（32字节）
       * </pre>
       *
       * <code>bytes state_root_hash = 2;</code>
       * @return The stateRootHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStateRootHash() {
        return stateRootHash_;
      }
      /**
       * <pre>
       * 状态根哈希（32字节）
       * </pre>
       *
       * <code>bytes state_root_hash = 2;</code>
       * @param value The stateRootHash to set.
       * @return This builder for chaining.
       */
      public Builder setStateRootHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        stateRootHash_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态根哈希（32字节）
       * </pre>
       *
       * <code>bytes state_root_hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateRootHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stateRootHash_ = getDefaultInstance().getStateRootHash();
        onChanged();
        return this;
      }

      private long blockTime_ ;
      /**
       * <pre>
       * 区块提议时间戳（毫秒级）
       * </pre>
       *
       * <code>uint64 block_time = 3;</code>
       * @return The blockTime.
       */
      @java.lang.Override
      public long getBlockTime() {
        return blockTime_;
      }
      /**
       * <pre>
       * 区块提议时间戳（毫秒级）
       * </pre>
       *
       * <code>uint64 block_time = 3;</code>
       * @param value The blockTime to set.
       * @return This builder for chaining.
       */
      public Builder setBlockTime(long value) {

        blockTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 区块提议时间戳（毫秒级）
       * </pre>
       *
       * <code>uint64 block_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        blockTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pohHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * PoH哈希（32字节）
       * </pre>
       *
       * <code>bytes poh_hash = 4;</code>
       * @return The pohHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPohHash() {
        return pohHash_;
      }
      /**
       * <pre>
       * PoH哈希（32字节）
       * </pre>
       *
       * <code>bytes poh_hash = 4;</code>
       * @param value The pohHash to set.
       * @return This builder for chaining.
       */
      public Builder setPohHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        pohHash_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * PoH哈希（32字节）
       * </pre>
       *
       * <code>bytes poh_hash = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPohHash() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pohHash_ = getDefaultInstance().getPohHash();
        onChanged();
        return this;
      }

      private long pohHeight_ ;
      /**
       * <pre>
       * PoH高度
       * </pre>
       *
       * <code>uint64 poh_height = 5;</code>
       * @return The pohHeight.
       */
      @java.lang.Override
      public long getPohHeight() {
        return pohHeight_;
      }
      /**
       * <pre>
       * PoH高度
       * </pre>
       *
       * <code>uint64 poh_height = 5;</code>
       * @param value The pohHeight to set.
       * @return This builder for chaining.
       */
      public Builder setPohHeight(long value) {

        pohHeight_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * PoH高度
       * </pre>
       *
       * <code>uint64 poh_height = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPohHeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pohHeight_ = 0L;
        onChanged();
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * 协议版本号
       * </pre>
       *
       * <code>uint64 version = 6;</code>
       * @return The version.
       */
      @java.lang.Override
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 协议版本号
       * </pre>
       *
       * <code>uint64 version = 6;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(long value) {

        version_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议版本号
       * </pre>
       *
       * <code>uint64 version = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000020);
        version_ = 0L;
        onChanged();
        return this;
      }

      private long slot_ ;
      /**
       * <pre>
       * 插槽号
       * </pre>
       *
       * <code>uint64 slot = 7;</code>
       * @return The slot.
       */
      @java.lang.Override
      public long getSlot() {
        return slot_;
      }
      /**
       * <pre>
       * 插槽号
       * </pre>
       *
       * <code>uint64 slot = 7;</code>
       * @param value The slot to set.
       * @return This builder for chaining.
       */
      public Builder setSlot(long value) {

        slot_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 插槽号
       * </pre>
       *
       * <code>uint64 slot = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000040);
        slot_ = 0L;
        onChanged();
        return this;
      }

      private long parentSlot_ ;
      /**
       * <pre>
       * 父插槽号
       * </pre>
       *
       * <code>uint64 parent_slot = 8;</code>
       * @return The parentSlot.
       */
      @java.lang.Override
      public long getParentSlot() {
        return parentSlot_;
      }
      /**
       * <pre>
       * 父插槽号
       * </pre>
       *
       * <code>uint64 parent_slot = 8;</code>
       * @param value The parentSlot to set.
       * @return This builder for chaining.
       */
      public Builder setParentSlot(long value) {

        parentSlot_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 父插槽号
       * </pre>
       *
       * <code>uint64 parent_slot = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentSlot() {
        bitField0_ = (bitField0_ & ~0x00000080);
        parentSlot_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString recentVotesHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 最近投票哈希（32字节）
       * </pre>
       *
       * <code>bytes recent_votes_hash = 9;</code>
       * @return The recentVotesHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRecentVotesHash() {
        return recentVotesHash_;
      }
      /**
       * <pre>
       * 最近投票哈希（32字节）
       * </pre>
       *
       * <code>bytes recent_votes_hash = 9;</code>
       * @param value The recentVotesHash to set.
       * @return This builder for chaining.
       */
      public Builder setRecentVotesHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        recentVotesHash_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最近投票哈希（32字节）
       * </pre>
       *
       * <code>bytes recent_votes_hash = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecentVotesHash() {
        bitField0_ = (bitField0_ & ~0x00000100);
        recentVotesHash_ = getDefaultInstance().getRecentVotesHash();
        onChanged();
        return this;
      }

      private long leaderScheduleEpoch_ ;
      /**
       * <pre>
       * 领导者调度周期
       * </pre>
       *
       * <code>uint64 leader_schedule_epoch = 10;</code>
       * @return The leaderScheduleEpoch.
       */
      @java.lang.Override
      public long getLeaderScheduleEpoch() {
        return leaderScheduleEpoch_;
      }
      /**
       * <pre>
       * 领导者调度周期
       * </pre>
       *
       * <code>uint64 leader_schedule_epoch = 10;</code>
       * @param value The leaderScheduleEpoch to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderScheduleEpoch(long value) {

        leaderScheduleEpoch_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 领导者调度周期
       * </pre>
       *
       * <code>uint64 leader_schedule_epoch = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderScheduleEpoch() {
        bitField0_ = (bitField0_ & ~0x00000200);
        leaderScheduleEpoch_ = 0L;
        onChanged();
        return this;
      }

      private long transactionsCount_ ;
      /**
       * <pre>
       * 交易数量
       * </pre>
       *
       * <code>uint64 transactions_count = 11;</code>
       * @return The transactionsCount.
       */
      @java.lang.Override
      public long getTransactionsCount() {
        return transactionsCount_;
      }
      /**
       * <pre>
       * 交易数量
       * </pre>
       *
       * <code>uint64 transactions_count = 11;</code>
       * @param value The transactionsCount to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionsCount(long value) {

        transactionsCount_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易数量
       * </pre>
       *
       * <code>uint64 transactions_count = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionsCount() {
        bitField0_ = (bitField0_ & ~0x00000400);
        transactionsCount_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString feeCalculatorHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 费用计算器哈希（32字节）
       * </pre>
       *
       * <code>bytes fee_calculator_hash = 12;</code>
       * @return The feeCalculatorHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFeeCalculatorHash() {
        return feeCalculatorHash_;
      }
      /**
       * <pre>
       * 费用计算器哈希（32字节）
       * </pre>
       *
       * <code>bytes fee_calculator_hash = 12;</code>
       * @param value The feeCalculatorHash to set.
       * @return This builder for chaining.
       */
      public Builder setFeeCalculatorHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        feeCalculatorHash_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 费用计算器哈希（32字节）
       * </pre>
       *
       * <code>bytes fee_calculator_hash = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeCalculatorHash() {
        bitField0_ = (bitField0_ & ~0x00000800);
        feeCalculatorHash_ = getDefaultInstance().getFeeCalculatorHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString txBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 交易布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes tx_bloom_filter = 13;</code>
       * @return The txBloomFilter.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTxBloomFilter() {
        return txBloomFilter_;
      }
      /**
       * <pre>
       * 交易布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes tx_bloom_filter = 13;</code>
       * @param value The txBloomFilter to set.
       * @return This builder for chaining.
       */
      public Builder setTxBloomFilter(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        txBloomFilter_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 交易布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes tx_bloom_filter = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxBloomFilter() {
        bitField0_ = (bitField0_ & ~0x00001000);
        txBloomFilter_ = getDefaultInstance().getTxBloomFilter();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString logBloomFilter_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 日志布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes log_bloom_filter = 14;</code>
       * @return The logBloomFilter.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLogBloomFilter() {
        return logBloomFilter_;
      }
      /**
       * <pre>
       * 日志布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes log_bloom_filter = 14;</code>
       * @param value The logBloomFilter to set.
       * @return This builder for chaining.
       */
      public Builder setLogBloomFilter(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        logBloomFilter_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 日志布隆过滤器（序列化后字节）
       * </pre>
       *
       * <code>bytes log_bloom_filter = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogBloomFilter() {
        bitField0_ = (bitField0_ & ~0x00002000);
        logBloomFilter_ = getDefaultInstance().getLogBloomFilter();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoBlockHeader)
    }

    // @@protoc_insertion_point(class_scope:ProtoBlockHeader)
    private static final Structure.ProtoBlockHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Structure.ProtoBlockHeader();
    }

    public static Structure.ProtoBlockHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoBlockHeader>
        PARSER = new com.google.protobuf.AbstractParser<ProtoBlockHeader>() {
      @java.lang.Override
      public ProtoBlockHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtoBlockHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBlockHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Structure.ProtoBlockHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return The header.
     */
    Structure.ProtoBlockHeader getHeader();
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     */
    Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code ProtoBlock}
   */
  public static final class ProtoBlock extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoBlock)
      ProtoBlockOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ProtoBlock.class.getName());
    }
    // Use ProtoBlock.newBuilder() to construct.
    private ProtoBlock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProtoBlock() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Structure.internal_static_ProtoBlock_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Structure.internal_static_ProtoBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Structure.ProtoBlock.class, Structure.ProtoBlock.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private Structure.ProtoBlockHeader header_;
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public Structure.ProtoBlockHeader getHeader() {
      return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.ProtoBlockHeader header = 1;</code>
     */
    @java.lang.Override
    public Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Structure.ProtoBlock)) {
        return super.equals(obj);
      }
      Structure.ProtoBlock other = (Structure.ProtoBlock) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Structure.ProtoBlock parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Structure.ProtoBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Structure.ProtoBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Structure.ProtoBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Structure.ProtoBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Structure.ProtoBlock prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoBlock)
        Structure.ProtoBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Structure.internal_static_ProtoBlock_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Structure.internal_static_ProtoBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Structure.ProtoBlock.class, Structure.ProtoBlock.Builder.class);
      }

      // Construct using Structure.ProtoBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetHeaderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Structure.internal_static_ProtoBlock_descriptor;
      }

      @java.lang.Override
      public Structure.ProtoBlock getDefaultInstanceForType() {
        return Structure.ProtoBlock.getDefaultInstance();
      }

      @java.lang.Override
      public Structure.ProtoBlock build() {
        Structure.ProtoBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Structure.ProtoBlock buildPartial() {
        Structure.ProtoBlock result = new Structure.ProtoBlock(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Structure.ProtoBlock result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Structure.ProtoBlock) {
          return mergeFrom((Structure.ProtoBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Structure.ProtoBlock other) {
        if (other == Structure.ProtoBlock.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Structure.ProtoBlockHeader header_;
      private com.google.protobuf.SingleFieldBuilder<
          Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       * @return The header.
       */
      public Structure.ProtoBlockHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? Structure.ProtoBlockHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder setHeader(Structure.ProtoBlockHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder setHeader(
          Structure.ProtoBlockHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder mergeHeader(Structure.ProtoBlockHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            header_ != null &&
            header_ != Structure.ProtoBlockHeader.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        if (header_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000001);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Structure.ProtoBlockHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return internalGetHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      public Structure.ProtoBlockHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              Structure.ProtoBlockHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.ProtoBlockHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder> 
          internalGetHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Structure.ProtoBlockHeader, Structure.ProtoBlockHeader.Builder, Structure.ProtoBlockHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProtoBlock)
    }

    // @@protoc_insertion_point(class_scope:ProtoBlock)
    private static final Structure.ProtoBlock DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Structure.ProtoBlock();
    }

    public static Structure.ProtoBlock getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoBlock>
        PARSER = new com.google.protobuf.AbstractParser<ProtoBlock>() {
      @java.lang.Override
      public ProtoBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtoBlock> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBlock> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Structure.ProtoBlock getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBlockHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoBlockHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoBlock_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017structure.proto\"\334\002\n\020ProtoBlockHeader\022\033" +
      "\n\023previous_block_hash\030\001 \001(\014\022\027\n\017state_roo" +
      "t_hash\030\002 \001(\014\022\022\n\nblock_time\030\003 \001(\004\022\020\n\010poh_" +
      "hash\030\004 \001(\014\022\022\n\npoh_height\030\005 \001(\004\022\017\n\007versio" +
      "n\030\006 \001(\004\022\014\n\004slot\030\007 \001(\004\022\023\n\013parent_slot\030\010 \001" +
      "(\004\022\031\n\021recent_votes_hash\030\t \001(\014\022\035\n\025leader_" +
      "schedule_epoch\030\n \001(\004\022\032\n\022transactions_cou" +
      "nt\030\013 \001(\004\022\033\n\023fee_calculator_hash\030\014 \001(\014\022\027\n" +
      "\017tx_bloom_filter\030\r \001(\014\022\030\n\020log_bloom_filt" +
      "er\030\016 \001(\014\"/\n\nProtoBlock\022!\n\006header\030\001 \001(\0132\021" +
      ".ProtoBlockHeaderb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoBlockHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoBlockHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoBlockHeader_descriptor,
        new java.lang.String[] { "PreviousBlockHash", "StateRootHash", "BlockTime", "PohHash", "PohHeight", "Version", "Slot", "ParentSlot", "RecentVotesHash", "LeaderScheduleEpoch", "TransactionsCount", "FeeCalculatorHash", "TxBloomFilter", "LogBloomFilter", });
    internal_static_ProtoBlock_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoBlock_descriptor,
        new java.lang.String[] { "Header", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
